export const GAME_END = 'GAME_END';
export const UPDATE_STATISTICS = 'UPDATE_STATISTICS';
export const CHANGE_TRAINING_ITERATIONS = 'CHANGE_TRAINING_ITERATIONS';
export const UPDATE_GAME = 'UPDATE_GAME';
export const TRAINING_END = 'TRAINING_END';
export const TRAINING_START = 'TRAINING_START';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';
export const CHANGE_GAME_TYPE = 'CHANGE_GAME_TYPE';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const START_REQUEST = 'START_REQUEST';
export const END_REQUEST = 'END_REQUEST';
export const CLOSE_ERROR = 'CLOSE_ERROR';
export const ERROR = 'ERROR';
export const RESET = 'RESET';
export const CHANGE_ONLY_AI = 'CHANGE_ONLY_AI';

// Grid
export const CHANGE_GRID_COLUMNS = 'CHANGE_GRID_COLUMNS';
export const CHANGE_GRID_ROWS = 'CHANGE_GRID_ROWS';

// Steps
export const CHANGE_GAME_FORM_STEP = 'CHANGE_GAME_FORM_STEP';
export const CHANGE_PLAYER_FORM_STEP = 'CHANGE_PLAYER_FORM_STEP';
export const CHANGE_MENU_STEP = 'CHANGE_MENU_STEP';
export const CHANGE_TRAININGS_FORM_STEP = 'CHANGE_TRAININGS_FORM_STEP';

// Player
export const CHANGE_PLAYER = 'CHANGE_PLAYER';

// Game
export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';

// Scores
export const UPDATE_SCORE_BOARD = 'UPDATE_SCORE_BOARD';

// Training
export const CHANGE_TRAININGS_ITERATIONS = 'CHANGE_TRAININGS_ITERATIONS';
export const START_TRAINING = 'START_TRAINING';

// Statistics
export const START_FETCHING_DATA = 'START_FETCHING_DATA';
export const SET_STATISTICS_DATABASES = 'SET_STATISTICS_DATABASES';
export const END_FETCHING_DATABASES = 'END_FETCHING_DATABASES';
export const SET_STATISTICS_DATA = 'SET_STATISTICS_DATA';
export const END_FETCHING_DATA = 'END_FETCHING_DATA';
export const START_FETCHING_DATABASES = 'START_FETCHING_DATABASES';
export const ADD_DATABASE = 'ADD_DATABASE';
export const REMOVE_DATABASE = 'REMOVE_DATABASE';
export const MARK_DATABASE = 'MARK_DATABASE';
export const MERGE_DATABASE = 'MERGE_DATABASE';

