export const MAKE_MOVE = 'MAKE_MOVE';
export const END_GAME = 'END_GAME';
export const START_GAME = 'START_GAME';
export const TOGGLE_IS_TRAINING = 'TOGGLE_IS_TRAINING';
export const SET_TRAINING_ITERATIONS = 'SET_TRAINING_ITERATIONS';